services:
  - type: web
    name: crm-django
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "0"
      - key: ALLOWED_HOSTS
        value: ""  # Set this in Render Dashboard to your service URL (e.g., crm-leads-cwml.onrender.com)
      - key: DATABASE_URL
        sync: false
      - key: ENV_TYPE
        value: prod
    healthCheckPath: /healthz/


