# Generated by Django 4.2.1 on 2025-09-15 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Status of Lead')),
                ('source', models.CharField(blank=True, max_length=255, null=True, verbose_name='Source of Lead')),
                ('description', models.TextField(blank=True, null=True)),
                ('follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('follow_up_status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done')], default='pending', max_length=16)),
                ('is_active', models.BooleanField(default=False)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('contact_first_name', models.CharField(blank=True, default='', max_length=255)),
                ('contact_last_name', models.CharField(blank=True, default='', max_length=255)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('contact_position_title', models.CharField(blank=True, default='', max_length=255)),
                ('contact_linkedin_url', models.URLField(blank=True, default='')),
                ('assigned_developer', models.CharField(blank=True, default='', help_text='Developer name (not a system user) assigned for development', max_length=255)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Employee assigned to work on this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to='common.profile')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'db_table': 'lead',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('message', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_notes', to='common.profile')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='leads.lead')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Lead Note',
                'verbose_name_plural': 'Lead Notes',
                'db_table': 'lead_notes',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='LeadNoteRead',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_by', to='leads.leadnote')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead Note Read',
                'verbose_name_plural': 'Lead Note Reads',
                'db_table': 'lead_note_reads',
                'unique_together': {('note', 'user')},
            },
        ),
    ]
