# Generated by Django 4.2.1 on 2025-09-20 07:38

from django.db import migrations


def populate_initial_lead_statuses(apps, schema_editor):
    LeadStatus = apps.get_model('common', 'LeadStatus')
    
    # Create initial statuses
    statuses = [
        ('new', 1),
        ('contacted', 2),
        ('qualified', 3),
        ('proposal', 4),
        ('negotiation', 5),
        ('closed', 6),
    ]
    
    for name, sort_order in statuses:
        LeadStatus.objects.get_or_create(
            name=name,
            defaults={'sort_order': sort_order}
        )

def reverse_populate_initial_lead_statuses(apps, schema_editor):
    LeadStatus = apps.get_model('common', 'LeadStatus')
    LeadStatus.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_clear_and_alter_lead_status'),
    ]

    operations = [
        migrations.RunPython(populate_initial_lead_statuses, reverse_populate_initial_lead_statuses),
    ]
