# Generated by Django 4.2.1 on 2025-09-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20250920_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='assigned_developer',
        ),
        migrations.AddField(
            model_name='lead',
            name='always_active',
            field=models.BooleanField(default=False),
        ),
    ]
