# Generated by Django 4.2.1 on 2025-09-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_remove_lead_assigned_developer_lead_always_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_project',
            field=models.BooleanField(default=False),
        ),
    ]
