# Generated by Django 4.2.1 on 2025-09-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_lead_is_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='priority',
            field=models.BooleanField(default=False),
        ),
    ]
