# Generated by Django 4.2.1 on 2025-12-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_lead_priority'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['is_project', 'is_active'], name='lead_is_proj_5e140f_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['follow_up_status', 'follow_up_at'], name='lead_follow__03f9d0_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to', 'is_active'], name='lead_assigne_f88827_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at'], name='lead_created_77f384_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='lead_status__be16a1_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['is_project', 'created_at'], name='lead_is_proj_394bb3_idx'),
        ),
    ]
