# Generated by Django 4.2.1 on 2025-01-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]

