# Generated by Django 4.2.1 on 2026-01-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_change_contact_phone_to_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='follow_up_status',
            field=models.CharField(
                blank=True,
                choices=[('pending', 'Pending'), ('done', 'Done')],
                max_length=16,
                null=True
            ),
        ),
    ]

