# Generated by Django 4.2.1 on 2026-01-18 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_leadlifecycle'),
        ('leads', '0009_remove_follow_up_status_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lifecycle',
            field=models.ForeignKey(
                blank=True,
                help_text='Lead lifecycle stage',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='common.leadlifecycle'
            ),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['lifecycle'], name='lead_lifecycl_4a7f2c_idx'),
        ),
    ]
