# Generated by Django 4.2.1 on 2026-01-20 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_leadlifecycle_id_alter_profile_role_and_more'),
        ('leads', '0010_lead_lifecycle'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lead',
            name='lead_lifecycl_4a7f2c_idx',
        ),
        migrations.AddField(
            model_name='lead',
            name='reminder_time_offset',
            field=models.CharField(blank=True, choices=[('exact', 'At exact time'), ('30min', '30 minutes before'), ('1hour', '1 hour before'), ('1day', '1 day before')], default='exact', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='send_reminder_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Employee assigned to work on this lead', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_leads', to='common.profile'),
        ),
        migrations.AddIndex(
            model_name='leadnote',
            index=models.Index(fields=['lead', 'created_at'], name='lead_notes_lead_id_d6cc25_idx'),
        ),
        migrations.AddIndex(
            model_name='leadnote',
            index=models.Index(fields=['author', 'created_at'], name='lead_notes_author__cb526c_idx'),
        ),
        migrations.AddIndex(
            model_name='leadnoteread',
            index=models.Index(fields=['user', 'created_at'], name='lead_note_r_user_id_201c74_idx'),
        ),
        migrations.AddIndex(
            model_name='leadnoteread',
            index=models.Index(fields=['note', 'user'], name='lead_note_r_note_id_91081a_idx'),
        ),
    ]
