# Generated by Django 4.2.1 on 2026-01-20 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_lead_reminder_email_sent_at'),
        ('leads', '0011_remove_lead_lead_lifecycl_4a7f2c_idx_and_more'),
    ]

    operations = [
    ]
