# Generated by Django 4.2.1 on 2026-01-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadLifecycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Lead Lifecycle',
                'verbose_name_plural': 'Lead Lifecycles',
                'db_table': 'lead_lifecycle',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
