# Generated by Django 4.2.1 on 2026-01-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_leadlifecycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadlifecycle',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.IntegerField(choices=[(0, 'MANAGER'), (1, 'EMPLOYEE')], default=1),
        ),
        migrations.DeleteModel(
            name='Leads',
        ),
    ]
